server:
#  Ӧ�ö˿�
  port: 8084
spring:
  datasource:
#    jdbc����url
    url: jdbc:mysql://60.205.218.96:3306/tr_edu?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    jdbc�����û���
    username: root
#    jdbc ��������
    password: xx770880
#    mysql ����
    driver-class-name: com.mysql.cj.jdbc.Driver
#    ����Դ
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-wait: 60000
      max-active: 20
      min-idle: 5
      stat-view-servlet:
        login-password: admin
        login-username: admin


# mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  typeAliasesPackage: org.fantu.trplan.edutrplan.domian
  type-enums-package: org.fantu.trplan.edutrplan.domian.enums
  global-config:
    db-config:
      id-type: UUID
    banner: true
  configuration:
    #�����շ幦��
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
